src/SimpleGpio.Web/Models/Constants.cs
using System.Device.Gpio;

namespace SimpleGpio.Models
{
    public static class Constants
    {
        public static readonly PinValue DefaultFirePinValue = PinValue.Low;
        public static readonly PinValue DefaultOffPinValue = PinValue.High;
        public const int DefaultFiringMs = 500;
        public const int RasPiPinCount = 28;
    }

    public enum FiringState
    {
        Ready,
        Armed,
        Firing,
        Fired
    }
}

src/SimpleGpio.Web/Models/FiringSystemOptions.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Device.Gpio;

namespace SimpleGpio.Models
{
    public class FiringSystemOptions
    {
        [Required]
        public PinValue FirePinValue { get; set; }
        public bool TimedFireMode { get; set; } = true;
        public int FiringMs { get; set; } = Constants.DefaultFiringMs;
        public List<FiringSystemPin> PinMappings { get; set; }
    }
}

src/SimpleGpio.Web/Models/FiringSystemPin.cs
namespace SimpleGpio.Models
{
    public class FiringSystemPin
    {
        public int GpioPin { get; set; }
        public string FiringAddress { get; set; }
        public FiringState State { get; set; } = FiringState.Ready;
    }
}

src/SimpleGpio.Web/Models/PinViewModel.cs
namespace SimpleGpio.Models
{
    public class PinViewModel
    {
        public int GpioPin { get; set; }
        public FiringState State { get; set; }
        public string DisplayName { get; set; }
    }
}

src/SimpleGpio.Web/Pages/Index.cshtml.cs
using SimpleGpio.Models;
using System;
using System.Collections.Generic;
using System.Device.Gpio;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SimpleGpio.Web
{
    public class IndexModel : PageModel
    {
        private static readonly GpioController _controller;
        private static readonly bool _liveGpioController;
        private static readonly int _pinCount;
        private static PinValue _firePinValue;
        private static PinValue _offPinValue;
        private static bool _timedFiringMode;
        private static int _firingMs;
        public static List<FiringSystemPin> LivePinStates { get; set; }
        static IndexModel()
        {
            // read "Fire" pin value from config
            _firePinValue = Startup.FiringSystemOptions.CurrentValue.FirePinValue;
            _offPinValue = _firePinValue == PinValue.High
                ? PinValue.Low : PinValue.High;

            // read "FiringMs" from config
            _firingMs = Startup.FiringSystemOptions.CurrentValue.FiringMs;

            // default to Raspberry Pi pin count
            _pinCount = Constants.RasPiPinCount;
            try
            {
                _controller = new GpioController();
                _pinCount = _controller.PinCount;
                _liveGpioController = true;
            }
            catch (System.PlatformNotSupportedException)
            {
                // bad hack for windows debugging
                _liveGpioController = false;
            }
            InitializeGpioPins();
        }

        private static void InitializeGpioPins()
        {
            // open all GPIO pins for output
            if (_controller != default)
            {
                foreach (var pin in Startup.FiringSystemOptions.CurrentValue.PinMappings)
                {
                    if (!_controller.IsPinOpen(pin.GpioPin))
                        _controller.OpenPin(pin.GpioPin, PinMode.Output);

                    if (_controller.GetPinMode(pin.GpioPin) != PinMode.Output)
                        _controller.SetPinMode(pin.GpioPin, PinMode.Output);
                }
            }

            WritePinsToGpio(Startup.FiringSystemOptions.CurrentValue.PinMappings);
            ReadLivePinStates();
        }
        private static void WritePinsToGpio(List<FiringSystemPin> pins)
        {
            // reset to ready/off state
            foreach (var pin in pins.Where(p => p.State == FiringState.Ready))
                WritePinValue(pin.GpioPin, _offPinValue);

            FirePins(pins.Where(p => p.State == FiringState.Armed));
        }

        private static void ReadLivePinStates()
        {
            for (var i = 0; i < _pinCount; i++)
            {
                var pin = LivePinStates.Single(p => p.GpioPin == i);

                // read states into static var
                if (_liveGpioController)
                {
                    var currentPinValue = _controller.Read(i);
                    if (currentPinValue == _firePinValue) pin.State = FiringState.Firing;
                    else if (currentPinValue == _offPinValue)
                    {
                        if (pin.State == FiringState.Firing) pin.State = FiringState.Fired;
                    }
                }
            }
        }
        private static void FirePins(IEnumerable<FiringSystemPin> pins)
        {
            // set to fire/on pin state
            Console.WriteLine(
                $"{(_liveGpioController ? "LIVE FIRE MODE: " : "(dry run): ")}Firing pins {string.Join(", ", pins.Select(p => p.GpioPin))}");

            foreach (var pin in pins) WritePinValue(pin.GpioPin, _firePinValue);

            // IF timed fire mode, wait for specified time, then turn off
            if (_timedFiringMode)
            {
                // create the firing timer
                var firingTimer = new System.Timers.Timer(_firingMs);

                // set the timer to run once
                firingTimer.AutoReset = false;

                // turn pins off after timer has elapsed
                firingTimer.Elapsed += (src, args) =>
                {
                    foreach (var pin in pins) WritePinValue(pin.GpioPin, _offPinValue);
                    Console.WriteLine($"Pins fired for {_firingMs} milliseconds");
                    firingTimer.Stop();
                    firingTimer.Dispose();
                };

                // start timer
                firingTimer.Enabled = true;
            }
        }

        private static void WritePinValue(int gpioPin, PinValue pinValue)
        {
            if (_liveGpioController) _controller.Write(gpioPin, pinValue);
            Console.WriteLine($"GPIO pin {gpioPin} set to {pinValue.ToString()}");
        }
        private void SetViewModelFromLivePinStates()
        {
            ReadLivePinStates();
            throw new NotImplementedException();
        }

        public void OnGet()
        {
            SetViewModelFromLivePinStates();
        }

        public ActionResult OnPostResetAllPins()
        {
            InitializeGpioPins();
            return RedirectToPage("Index");
        }
        [BindProperty]
        public List<PinViewModel> Pins { get; set; }
        public ActionResult OnPost()
        {
            ReadLivePinStates();
            List<FiringSystemPin> changedPinStates = new();

            // because of disable behavior on inputs, only new pinsettings will be sent from form
            // https://stackoverflow.com/questions/7357256/disabled-form-inputs-do-not-appear-in-the-request
            foreach (var pinState in LivePinStates)
            {
                var viewModelPin = Pins.Single(p => p.GpioPin == pinState.GpioPin);

                // if user passed in a new state
                if (viewModelPin.State != pinState.State)
                {
                    changedPinStates.Add(new FiringSystemPin
                    {
                        GpioPin = pinState.GpioPin,
                        FiringAddress = pinState.FiringAddress,
                        State = viewModelPin.State
                    });
                }
            }

            WritePinsToGpio(changedPinStates);
            return RedirectToPage("Index");
        }
    }
}

src/SimpleGpio.Web/Pages/Index.cshtml
@page "/"
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model SimpleGpio.Web.IndexModel

<form method="post">
    <h1 class="display-1 text-center">GPIO Pin Controller</h1>
    <button class="btn btn-lg btn-primary w-100 mb-3" type="submit">Set Pins Now</button>
    <div class="row">

        @foreach (var pinSetting in Model.PinSettingsViewModel.OrderBy(p => p.Key))
        {
            <div class="col-6">
                <div class="form-check form-switch mb-3">
                    <label class="form-check-label h4 w-100" for="pin-@pinSetting.Key">
                        <span class="badge w-100 p-2@(pinSetting.Value ? " bg-danger" : " bg-secondary")">
                            Pin @pinSetting.Key
                        </span>
                    </label>
                    <input asp-for="@Model.PinSettingsViewModel[pinSetting.Key]"
                    class="form-check-input mt-2@(pinSetting.Value ? " bg-danger border-danger" : string.Empty)"
                    disabled=@pinSetting.Value checked=@pinSetting.Value id="pin-@pinSetting.Key">
                </div>
            </div>
        }
    </div>
    <button asp-page-handler="ResetAllPins" class="btn btn-lg btn-danger w-100 mb-3">Reset All Pins</button>
</form>

<script type="text/javascript">
    document.querySelectorAll('input.form-check-input').forEach(switchInput => {
        switchInput.addEventListener('input', function (event) {
            const pinSwitch = event.currentTarget;
            const badge = pinSwitch.previousElementSibling.querySelector('span');
            if (pinSwitch.checked) {
                // add styles
                badge.classList.remove('bg-secondary')
                badge.classList.add('bg-success')
                pinSwitch.classList.add('bg-success')
                pinSwitch.classList.add('border-success')
            }
            else {
                // add styles
                badge.classList.add('bg-secondary')
                badge.classList.remove('bg-success')
                pinSwitch.classList.remove('bg-success')
                pinSwitch.classList.remove('border-success')
            }
        })
    });
</script>

src/SimpleGpio.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/bootstrap-5.0.0-beta3-dist/css/bootstrap.css" />
</head>

<body class="d-flex flex-column h-100 bg-dark text-light">
    <div class="container">
        @RenderBody()
    </div>
</body>

</html>